void initializeCharBuffer();
char *getCharBuffer();
void addCharElement(char);
void addCharElements(char *);
void removeCharLast();
void destroyCharBuffer();
void rewindCharPointer();
int charSize();
void initializeIntBuffer();
void addIntElement(int);
void removeIntLast();
void destroyIntBuffer();
void rewindIntPointer();
int intSize();
void fillIntArrayWithBuffer(int *);
int isInIntBuffer(int);
